---
- hosts: all
  become: true

  vars:
    # NOTICE!!!:
    # DO NOT PUT PLAIN TEXT PASSWORDS HERE!
    # use encrypted passwords or put them in Ansible vault
    # but this is just a demo
    vaulted_password: welcome1


  tasks:
  - name: update.
    apt:
      update_cache: true
      upgrade: dist

  - name: install visual studio code.
    snap:
      name: code
      classic: true

  - name: Add the admin group.
    group:
      name: admin
      state: present
  # https://computingforgeeks.com/manage-users-and-groups-on-linux-using-ansible/
  - name: add user joe.
    user:
      name: joe
      group: admin
      createhome: true
      password: "{{ vaulted_password | password_hash('sha512') }}"

  - name: install ansible and linters.
    apt:
      pkg:
        - ansible
        - yamllint
        - ansible-lint
  - name: remove unwanted packages.
    apt:
      pkg:
        - thunderbird
        - libreoffice*
        - rhythmbox
      state: absent

  - name: Update apt-get repo and cache.
    apt:
      update_cache: true
  - name: Upgrade all apt packages
    apt:
      upgrade: dist
      force_apt_get: true

  - name: install curl.
    snap:
      name: curl

# install maven
# install jdk and remove open jdk


# https://www.ansibletutorials.com/adding-users
# install kubernetes and docker is a schwaz - do it in a separate playbook
#https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/
