# _*_ mode: ruby _*_
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # General Vagrant VM configurations
  config.vm.box = "geerlingguy/centos8"
  config.ssh.insert_key = false
  config.vm.synced_folder ".","/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.linked_clone = true
  end

  # Application server 1.
  config.vm.define "app1" do |app|
    app.vm.hostname = "orcl-app1.jstl.com"
    app.vm.network :public_network, ip:"192.168.0.204"
  end

  # Application server 2.
  config.vm.define "app2" do |app|
    app.vm.hostname = "orcl-app2.jstl.com"
    app.vm.network :public_network, ip:"192.168.0.205"
  end

  # Database server 1.
  config.vm.define "db" do |app|
    app.vm.hostname = "orcl-db.jstl.com"
    app.vm.network :public_network, ip:"192.168.0.206"
  end
end
